### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.mgmt.cosmosdb.models.error_response_py3.ErrorResponse
  - azure.mgmt.cosmosdb.models.error_response_py3.ErrorResponseException
  fullName: azure.mgmt.cosmosdb.models.error_response_py3
  langs:
  - python
  module: azure.mgmt.cosmosdb.models.error_response_py3
  name: error_response_py3
  source:
    id: error_response_py3
    path: azure-mgmt-cosmosdb\azure\mgmt\cosmosdb\models\error_response_py3.py
    remote:
      branch: northstar
      path: azure-mgmt-cosmosdb\azure\mgmt\cosmosdb\models\error_response_py3.py
      repo: https://github.com/mmacy/azure-sdk-for-python
    startLine: 0
  type: module
  uid: azure.mgmt.cosmosdb.models.error_response_py3
references:
- fullName: azure.mgmt.cosmosdb.models.error_response_py3.ErrorResponse
  isExternal: false
  name: ErrorResponse
  parent: azure.mgmt.cosmosdb.models.error_response_py3
  uid: azure.mgmt.cosmosdb.models.error_response_py3.ErrorResponse
- fullName: azure.mgmt.cosmosdb.models.error_response_py3.ErrorResponseException
  isExternal: false
  name: ErrorResponseException
  parent: azure.mgmt.cosmosdb.models.error_response_py3
  uid: azure.mgmt.cosmosdb.models.error_response_py3.ErrorResponseException
